version: "3.2"
services:
  php:
    build:
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ../sc3/:/var/www/html/
    container_name: "${PHP_NAME}"
    depends_on:
      - mysql

  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ../sc3/:/var/www/html/
    container_name: "${APACHE_NAME}"

  mysql:
    image: mysql:${MYSQL_VERSION}
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: "${MYSQL_NAME}"

  redis:
    image: redis:${REDIS_VERSION}-alpine
    networks:
      - backend
    ports:
      - "6379:6379"

networks:
  backend:
  frontend:
