#controllers:
#    resource: ../../src/Controller/
#    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

localization.module.controllers:
    resource: ../../src/LocalizationModule/Api
    type: annotation