#controllers:
#    resource: ../../src/Controller/
#    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

Location.module.controllers:
    resource: ../../src/System/Main/Location/Api
    type: annotation